GET http://localhost:3000/api/login

###
GET http://localhost:3000/captainsLog/6348f88e67b7a5f9a8402f53

###
POST http://localhost:3000/captainsLog
Content-Type: application/json

{
    "title":"captain1",
    "entry":"iafn",
    "shipIsBroken":true
}

### 
DELETE  http://localhost:3000/captainsLog/6348f88e67b7a5f9a8402f53

### 
PATCH  http://localhost:3000/captainsLog/6348f7f516a3eab92a1aef66
Content-Type: application/json

{
    "title":"updatedCaptain"
}